# Generated by Django 3.0.8 on 2020-07-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_cateogory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cateogory',
        ),
    ]
