# Generated by Django 3.0.8 on 2020-07-21 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_cateogory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cateogory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Cateogory'),
        ),
    ]
